### ISSUE TITLE
drag and drop (drag Katzenfutter zu triggerbox der Katze um die Coin zu bekommen)

### ISSUE THREAD

**Issue by Inner-e** [4ahmnm2021-G3-G4/01-maze-audiocode-inner#4]
drag and drop script von SteamVR nicht im Projekt gefunden (SteamVR advanced?)

**Comment by smeerws** [comment]
Genauere Information bitte, kann so leider nicht weiterhelfen. Wo soll das verwendet werden, auf welchem Object
