### ISSUE TITLE
CollectCoin Script SetActive(false) geht nicht

### ISSUE THREAD

**Issue by Inner-e** [4ahmnm2021-G3-G4/01-maze-audiocode-inner#6]
GameObject.active is obsolete

**Comment by smeerws** [comment]
was ist genau das Ziel?
Ich nehme an, coin einsammeln zum Zähler dazuzählen und zerstören. Wenn ich mit meinen Händen die Coin einsammeln möchte würde ich ein Script für Coin schreiben. Das auf die Coins draufziehen. Sobald coin on collision oder on trigger enter je nachdem was du machen möchtest, im Scriptable Object count erhöhen und coin zerstört sich selbst.

**Comment by Inner-e** [comment]
Der Script sollte bei der Collision von dem Player Collider mit den collider der Münzen auslösen, dass die Münze destroyed und der counter per Münze einen wert hochzählt(1/3 --> 2/3). Jedoch funktioniert die Methode im Script nicht und die Münze wird nicht destroyed wie auch der Wert nicht meh wird.
